---
ignore_projects:
  any:
  - admin
  - services
  fokus:
  - sarjo3
images:
  any:
    cirros-0.3.4:
      diskFormat: qcow2
      path: "/etc/softfire/images/cirros-0.4.0-x86_64-disk.img"
      shared: true
      containerFormat: bare
      size: ''
    test_img-ubuntu-14.4.6:
      diskFormat: qcow2
      path: "/etc/softfire/images/cirros-0.4.0-x86_64-disk.img"
      shared: true
      containerFormat: bare
      size: ''
  fokus:
    cirros-0.3.4:
      diskFormat: qcow2
      path: "/etc/softfire/images/cirros-0.4.0-x86_64-disk.img"
      shared: true
      containerFormat: bare
      size: ''
    test_img-ubuntu-16.8.6:
      diskFormat: qcow2
      path: "/etc/softfire/images/cirros-0.4.0-x86_64-disk.img"
      shared: true
      containerFormat: bare
      size: ''
security_group:
  any:
  - test12
  - any_test20
  - default
  fokus:
  - test12
  - f_test13
  - f_test14
networks:
  fokus:
  - name: softfire-network
    shared: false
    router:external: true
  - name: softfire-internal
    shared: true
    router:external: false
ignore_floating_ips:
  any:
  - 192.168.161.11
  - 192.168.161.3
  - 192.168.165.9
  fokus:
  - 172.20.30.93
  - 172.20.30.104
check-vm:
  experiment-manager:
    username: admin
    password: softfire
    ip: localhost
    port: '5080'
  nfvo:
    username: admin
    password: openbaton
    ip: localhost
    port: '8080'
    https: 'false'
  ignore-vm-ids:
  - vm-id-here
  ignore-nsr-ids:
  - nsr-id-here
